spring:
  datasource:
    url: jdbc:postgres://c322_postgresql_user:pKVeSIPQr3Cs519DccrbzPi3VgZJSCh3@dpg-coha0uvsc6pc73ak5lk0-a.ohio-postgres.render.com/c322_postgresql
    username: c322_postgresql_user
    password: pKVeSIPQr3Cs519DccrbzPi3VgZJSCh3


    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgresSQLDialect

      sql:
        init:
          mode: always
